
ny_taxi_test:
  outputs:
    dev:
      type: postgres
      threads: 32
      host: "{{ env_var('POSTGRES_HOST') }}"
      user: "{{ env_var('POSTGRES_USER') }}"
      pass: "{{ env_var('POSTGRES_PASSWORD') }}"
      port: "{{ env_var('POSTGRES_PORT') | as_number }}"
      dbname: ny_taxi_database
      schema: staging # e.g. dbt_alice
    production:
      type: postgres
      threads: 32
      host: idowupostgresserver.postgres.database.azure.com
      user: idowuadmin
      pass: Ekabagoodness@96
      port: 5432
      dbname: ny_taxi_database
      schema: staging

  target: "{{ env_var('DBT_TARGET') }}"



# ny_taxi:
#   outputs:
#     dev:
#       type: postgres
#       threads: 32
#       host: localhost
#       user: idowuuser
#       pass: passwordguddy
#       port: 5433
#       dbname: ny_taxi_database
#       schema: staging # e.g. dbt_alice
#   target: dev
