name: nyc_taxi_actions
on: 
    push:
        branches: [ "master" ]
jobs:
    build:
        runs-on: ubuntu-latest 
        steps:
            - name: Checkout the Code
              uses: actions/checkout@v2 

            - name: instalL python
              uses: actions/setup-python@v5
              with:
                python-version: '3.10'
            - name: test the codef
              run: |
                pip install pytest 
                pip install -r ./docker_sql/requirements.txt
                pytest ./docker_sql/test/test_download_data.py
              working-directory: ${{ github.workspace }}

            - name: get the tag for the docker image and tag
              id: increment-docker-image-git-tag
              shell: bash
              run: |
                chmod +x ./docker_sql/git_hub_workflow.sh 
                bash ./docker_sql/git_hub_workflow.sh
              working-directory: ${{ github.workspace }}

            - name: Login to Docker Hub, build image and push
              uses: docker/login-action@v1
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }} 
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: build image and upload
              env:
                DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }} 
                DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
                DOCKER_SECRET_TOKEN: ${{ secrets.DOCKER_SECRET_TOKEN }}
                DOCKER_REPOSITORY_IMAGE: idowuilekura/nyc_taxi_data
                IMAGE_TAG: ${{ steps.increment-docker-image-git-tag.outputs.git-tag }}
              run: |
                docker build -t $DOCKER_REPOSITORY_IMAGE:$IMAGE_TAG -f ./docker_sql
                docker push $DOCKER_REPOSITORY_IMAGE:$IMAGE_TAG
              working-directory: ${{ github.workspace }}


            